# Generated by Django 5.0.4 on 2024-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvweek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartline',
            name='program_genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр програми'),
        ),
        migrations.AlterField(
            model_name='chartline',
            name='program_title',
            field=models.CharField(max_length=200, verbose_name='Назва програми'),
        ),
        migrations.AlterField(
            model_name='chartline',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час початку'),
        ),
    ]
