version: '3.7'

services:
  svitloweb:
    build: .
    container_name: svitlo-backend
    command: sh /app/entrypoint.prod.sh
    volumes:
      - .:/app/
    expose:
      - 8000
    ports:
      - "8096:8000"
    env_file:
      - .env.dev
    depends_on:
      - svitlodbd
      - svitloredis

  svitlodbd:
    image: postgres
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.db

  svitloredis:
    image: redis:latest
    container_name: docker-svitlo-redis
    ports:
      - "17379:6379"