# Generated by Django 5.0.4 on 2024-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_genre_projectgenres'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
