# Generated by Django 5.0.4 on 2024-04-18 00:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTvManualStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('about_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Назва соціальної мережі', max_length=255)),
                ('logotype', models.FileField(help_text='Завантажте логотип соціальної мережі', max_length=255, upload_to='')),
                ('url', models.URLField(help_text='URL посилання на соціальну мережу')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeOnlineTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('online_provider_url', models.URLField(default='#')),
                ('logo_provider', models.ForeignKey(blank=True, help_text='Логотип провайдера', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_tv', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Про нас назва блоку')),
                ('about_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Про нас заголовок')),
                ('about_description', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Про нас текст опису')),
                ('manual_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Налаштування приймача')),
                ('manual_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок блоку налаштування')),
                ('manual_text', models.CharField(blank=True, max_length=550, null=True, verbose_name='Текст налаштувань')),
                ('online_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Онлайн провайдери назва блоку')),
                ('online_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Онлайн провайдери заголовок')),
                ('online_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Онлайн провайдери опис')),
                ('about_picture', models.ForeignKey(blank=True, help_text='малюнок дло блоку Про нас', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageSliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('desktop_picture', models.ForeignKey(blank=True, help_text='Малюнок слайдеру десктоп версія', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('mobile_picture', models.ForeignKey(blank=True, help_text='Малюнок слайдеру мобільна версія', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
