# Generated by Django 5.0.4 on 2024-04-10 20:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='hometvmanualstep',
            name='step_picture',
            field=models.ForeignKey(blank=True, help_text='Малюнок дло блоку Про нас', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Назва соціальної мережі', max_length=255)),
                ('logotype', models.ImageField(help_text='Завантажте логотип соціальної мережі', max_length=255, upload_to='')),
                ('url', models.URLField(help_text='URL посилання на соціальну мережу')),
                ('site_setting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='home.socialmediasettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
