# Generated by Django 5.0.4 on 2024-04-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='report_pdf',
            field=models.ForeignKey(blank=True, help_text='Структура власності', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
