# Generated by Django 5.0.4 on 2024-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_socialmediasettings_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='logotype',
            field=models.FileField(help_text='Завантажте логотип соціальної мережі', max_length=255, upload_to=''),
        ),
    ]
