# Generated by Django 5.0.4 on 2024-05-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactdatasettings_contactdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdatasettings',
            options={'verbose_name': 'Налаштування контактних даних'},
        ),
        migrations.AddField(
            model_name='contactdata',
            name='post_addr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
