# Generated by Django 5.0.4 on 2024-07-29 11:07

import tools.owerwritefile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contactdatasettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpdf',
            name='report',
            field=models.FileField(help_text='Структура власності', max_length=255, storage=tools.owerwritefile.OverwriteStorage(), upload_to=''),
        ),
    ]
